version: '3.7'

services:

  db:
    image: mariadb:10.5
    container_name: course_alura_jpa_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course_alura
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  adminer:
    image: adminer
    container_name: course_adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend

networks:
  backend:
    driver: bridge
    name: course_alura_jpa_network
